# Generated by Django 2.1.15 on 2020-10-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0088_order_del_print_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw_pi',
            name='update_status',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_del',
            name='lianchang',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order_del',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_del',
            name='total_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order_del',
            name='update_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packing',
            name='lianchang',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
