# Generated by Django 2.1.15 on 2020-10-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0089_auto_20201010_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='Rework',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order_del',
            name='refund',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='technology',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
